//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kapi
    {
        public int Id { get; set; }
        public string KapiNo { get; set; }
        public Nullable<int> MahalleKodu { get; set; }
        public string koordinatlar { get; set; }
    }
}
